# Используем официальный образ PostgreSQL
FROM postgres:latest

# Устанавливаем переменные окружения для настройки PostgreSQL
ENV POSTGRES_USER delpi5
ENV POSTGRES_PASSWORD 123123
ENV POSTGRES_DB postgres

# Открываем порт 5432
EXPOSE 5432
